### ISSUE TITLE
merge trufont/defcon patches back into upstream typesupply/defcon?

### ISSUE THREAD

**Issue by anthrotype** [trufont/defcon#5]
What needs to be done to merge the changes in trufont's defcon fork back into @typesupply's upstream repository?

I was about to make pull a request for some minor defcon stuff, but then I asked myself... "hmm, where shall I send it to?" :)

**Comment by anthrotype** [comment]
At first glance, the set of changes looks quite big:
https://github.com/typesupply/defcon/compare/ufo3...trufont:python3-ufo3?expand=1

It seems like a few commits were cherry-picked from the upstream repo, so they may show up as duplicate. Maybe it would be better to make a new temporary branch where commits are cleaned up (rebased, squeezed, etc.) before sending a PR. 

Also, it appears that Adrien's `python3-ufo3` branch is Python 3 only. Ideally, if we want to merge it back into typesupply/ufo3, we will need to make it `py23`-compatible. @moyogo started looking into this some time ago, but I don't know whether he's ever finished that: https://github.com/moyogo/defcon/tree/py23-ufo3

@adrientetar any thoughts?

**Comment by adrientetar** [comment]
It's on my TODO list, but right now I'm finishing a large refactoring of TruFont. I'll do that afterwards.

> What needs to be done to merge the changes in trufont's defcon fork back into @​typesupply's upstream repository?

rebase/cherry-pick appropriate patches

**Comment by anthrotype** [comment]
Excellent, thanks Adrien. Just let me know if I can be of any help.

**Comment by adrientetar** [comment]
Thanks!

**Comment by typesupply** [comment]
> Ideally, if we want to merge it back into typesupply/ufo3, we will need to make it py23-compatible.

Yes. I don't want to switch solely to Python 3. There are too many things built on defcon that have other dependencies that aren't yet Python 3 compatible.

**Comment by adrientetar** [comment]
I probably won't have time to do this until after London.
